version: '3.8'
services:
  checklistplus-app:
     image: 172.31.160.1:5000/checklistreact-app:v2
     ports:
      - "3007:80"
     volumes:
      - /usr/local/share/workspace/docker_compose/nginx_data:/usr/share/nginx/html/checklistplusv2
     depends_on:
      - checklistplusv2-php
      - checklistplus-mysql
     networks:
      - my-checklist-plus-network
      - jenkins-overlay
     deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 
  checklistplus-mysql:
      image: 172.31.160.1:5000/checklistreact-mysql:v2
      environment:
        - MYSQL_ROOT_PASSWORD=db
        - MYSQL_DATABASE=checklistplusv2
        - MYSQL_ROOT_HOST=%
      networks:
        - my-checklist-plus-network
        - jenkins-overlay
      restart: always
      ports:
       - 3309:3306
      volumes:
        - ./mysql_custom/my.cnf:/etc/my.cnf
        - ./mysql_data/:/var/lib/mysql
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure   
  checklistplusv2-php:
       image: 172.31.160.1:5000/checklistreact-php:v2
       networks:
        - my-checklist-plus-network
        - jenkins-overlay
       ports:
        - 3010:9000
       restart: always 
       volumes:
        - /usr/local/share/workspace/docker_compose/nginx_data/html/api:/var/www/html/checklistv2/api
       depends_on:
        - checklistplus-mysql
       deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
           
networks:
  my-checklist-plus-network:
    driver: overlay
    attachable: true
  jenkins-overlay:
    external: true     
