version: '3.8'
services:
  checklistplus-app:
     image: 192.168.0.103:5000/checklistplusv2-app:v2
     ports:
      - "3007:80"
     volumes:
      - ./checklist-data/html:/usr/share/nginx/html/checklistplusv2
     depends_on:
      - checklistplusv2-php
      - checklistplus-mysql
     networks:
      - my-checklist-plus-network  
     deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 
  checklistplus-mysql:
      image: 192.168.0.103:5000/checklistplusv2-mysql:v2
      environment:
        - MYSQL_ROOT_PASSWORD=db
        - MYSQL_DATABASE=checklistplusv2
        - MYSQL_ROOT_HOST=%
      networks:
        - my-checklist-plus-network
      restart: always
      ports:
       - 3309:3306
      volumes:
        - ./mysql_custom/my.cnf:/etc/my.cnf
        - ./mysql_data/:/var/lib/mysql
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure   
  checklistplusv2-php:
       image: 192.168.0.103:5000/checklistplusv2-php:v2
       networks:
        - my-checklist-plus-network
       ports:
        - 3010:9000
       restart: always 
       volumes:
        - ./backend:/var/www/html/checklistv2/api
       depends_on:
        - checklistplus-mysql
       deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
           
networks:
  my-checklist-plus-network:
    driver: overlay
    attachable: true
